"post-root-package-install": "Proximify\\AppCLI::auto",
        "post-create-project-cmd": "Proximify\\AppCLI::auto",
        "pre-install-cmd": "Proximify\\AppCLI::auto",
        "post-install-cmd": "Proximify\\AppCLI::auto",
        "pre-status-cmd": "Proximify\\AppCLI::auto",
        "post-status-cmd": "Proximify\\AppCLI::auto",
        "pre-update-cmd": "Proximify\\AppCLI::auto",
        "post-update-cmd": "Proximify\\AppCLI::auto",
        "pre-package-install": "Proximify\\AppCLI::auto",
        "post-package-install": "Proximify\\AppCLI::auto",
        "pre-package-update": "Proximify\\AppCLI::auto",
        "post-package-update": "Proximify\\AppCLI::auto",
        "pre-package-uninstall": "Proximify\\AppCLI::auto",
        "post-package-uninstall": "Proximify\\AppCLI::auto"